/**
 * Build Script: Scan CSS files for design-token var() usages at build time
 * Output: src/generated/token-usage.ts
 *
 * The /tokens audit view uses this data to detect missing tokens (CSS
 * referencing a var that doesn't exist), bad usage (CSS referencing system or
 * global tokens directly), and component tokens never used by any CSS file.
 */

import fs from 'fs';
import path from 'path';

interface TokenUsage {
  varName: string;
  file: string;
  line: number;
}

const SRC_DIR = path.join(process.cwd(), 'src');
// Generated token output — every token "appears" there by definition.
const EXCLUDED = new Set(['src/tokens/design-tokens.css']);

const VAR_PATTERN = /var\(\s*(--(?:components|system|global)-tokens--[a-z0-9-]+)/g;

function collectCssFiles(dir: string, out: string[] = []): string[] {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) collectCssFiles(fullPath, out);
    else if (entry.isFile() && entry.name.endsWith('.css')) out.push(fullPath);
  }
  return out;
}

function main() {
  const usages: TokenUsage[] = [];
  const cssFiles = collectCssFiles(SRC_DIR)
    .map((f) => path.relative(process.cwd(), f))
    .filter((f) => !EXCLUDED.has(f))
    .sort();

  for (const file of cssFiles) {
    const lines = fs.readFileSync(file, 'utf-8').split('\n');
    lines.forEach((text, index) => {
      for (const match of text.matchAll(VAR_PATTERN)) {
        usages.push({ varName: match[1], file, line: index + 1 });
      }
    });
  }

  const outDir = path.join(process.cwd(), 'src', 'generated');
  const outFile = path.join(outDir, 'token-usage.ts');

  fs.mkdirSync(outDir, { recursive: true });

  const content = [
    '// Auto-generated by build:usage — do not edit manually',
    '',
    'export interface TokenUsage {',
    '  varName: string;',
    '  file: string;',
    '  line: number;',
    '}',
    '',
    `export const tokenUsages: TokenUsage[] = ${JSON.stringify(usages, null, 2)};`,
    '',
  ].join('\n');

  fs.writeFileSync(outFile, content);
  console.log(
    `✅ Written ${usages.length} usages from ${cssFiles.length} CSS files to src/generated/token-usage.ts`,
  );
}

main();
