/**
 * Token audit engine for the /tokens page.
 *
 * Re-parses the same JSON sources as buildTokenGraph (cheap, runs once) to get
 * the reference target of every token, and cross-checks them against the
 * resolved graph plus the CSS usage data generated by build:usage.
 *
 * Issue node ids follow the graph-builder convention (`level::path`) so every
 * token issue can open the TokenInspector.
 */

import globalJson from './json/global.json';
import systemLightJson from './json/system-light.json';
import systemDarkJson from './json/system-dark.json';
import componentsJson from './json/components.json';
import { tokenUsages } from '../generated/token-usage';
import {
  parseTokens,
  findReferencedPath,
  formatValue,
  type TokenMap,
} from './parser';
import type { TokenGraph } from './graph-builder';

export type AuditSeverity = 'error' | 'warning' | 'info';

export type AuditCheckId =
  | 'broken-reference'
  | 'missing-token'
  | 'bad-usage'
  | 'raw-value'
  | 'duplicate'
  | 'unused';

export interface AuditCheck {
  id: AuditCheckId;
  title: string;
  severity: AuditSeverity;
  description: string;
}

export const AUDIT_CHECKS: AuditCheck[] = [
  {
    id: 'broken-reference',
    title: 'Broken references',
    severity: 'error',
    description:
      'Tokens whose reference target cannot be resolved — the CSS build emits the unresolved reference string.',
  },
  {
    id: 'missing-token',
    title: 'Missing tokens in CSS',
    severity: 'error',
    description:
      'CSS files reference a token variable that does not exist in any token JSON, so the property resolves to nothing.',
  },
  {
    id: 'bad-usage',
    title: 'Bad usage in CSS',
    severity: 'warning',
    description:
      'CSS referencing system or global tokens directly. The rule is CSS → component tokens → system → global.',
  },
  {
    id: 'raw-value',
    title: 'Raw values where an alias is expected',
    severity: 'warning',
    description:
      'Component tokens must alias system tokens, and system (light) tokens must alias globals. Level-skipping references are flagged too.',
  },
  {
    id: 'duplicate',
    title: 'Duplicate values',
    severity: 'info',
    description:
      'Tokens at the same level and type sharing an identical resolved value — candidates for consolidation.',
  },
  {
    id: 'unused',
    title: 'Unused tokens',
    severity: 'info',
    description:
      'Globals no system token references, system tokens no component token references, and component tokens never used in CSS.',
  },
];

export interface AuditLocation {
  file: string;
  line: number;
}

export interface AuditIssue {
  check: AuditCheckId;
  severity: AuditSeverity;
  message: string;
  /** Graph node (`level::path`) — clickable in the UI to open the inspector. */
  nodeId?: string;
  /** Extra nodes involved (e.g. members of a duplicate-value group). */
  relatedNodeIds?: string[];
  cssVar?: string;
  locations?: AuditLocation[];
}

export interface AuditReport {
  issues: AuditIssue[];
  byCheck: Record<AuditCheckId, AuditIssue[]>;
  counts: Record<AuditSeverity, number>;
}

/**
 * Comparison-safe normalization: formatValue adds units based on each side's
 * own path/type, so "20px" vs "20" would be a false drift — compare the
 * numeric part when both sides are numbers.
 */
function normalizeValue(value: string | number, type: string, path: string): string {
  const formatted = formatValue(String(value), type, path).toLowerCase().trim();
  const numeric = formatted.endsWith('px') ? formatted.slice(0, -2) : formatted;
  if (numeric !== '' && !isNaN(Number(numeric))) return String(Number(numeric));
  return formatted;
}

function nodeIdFor(level: 'global' | 'system' | 'component', path: string): string {
  return `${level}::${path}`;
}

export function runTokenAudit(graph: TokenGraph): AuditReport {
  const globalMap = parseTokens(globalJson, 'global tokens', 'global');
  const systemLightMap = parseTokens(systemLightJson, 'system tokens', 'system');
  const systemDarkMap = parseTokens(systemDarkJson, 'system tokens', 'system');
  const componentMap = parseTokens(componentsJson, 'components tokens', 'component');

  const lightSpace: TokenMap = { ...globalMap, ...systemLightMap, ...componentMap };
  const darkSpace: TokenMap = { ...globalMap, ...systemDarkMap };

  const issues: AuditIssue[] = [];

  // --- 1. Broken references (per theme resolution space) ---
  for (const path in lightSpace) {
    const token = lightSpace[path];
    if (!token.isReference || !token.referencePath) continue;
    if (!findReferencedPath(token.referencePath, lightSpace)) {
      issues.push({
        check: 'broken-reference',
        severity: 'error',
        message: `References "${token.referencePath}", which does not exist.`,
        nodeId: nodeIdFor(token.level, path),
      });
    }
  }
  for (const path in systemDarkMap) {
    const token = systemDarkMap[path];
    if (!systemLightMap[path]) {
      issues.push({
        check: 'broken-reference',
        severity: 'error',
        message: 'Dark override has no light-mode counterpart — undefined in light mode.',
        nodeId: nodeIdFor('system', path),
      });
    }
    if (!token.isReference || !token.referencePath) continue;
    if (!findReferencedPath(token.referencePath, darkSpace)) {
      issues.push({
        check: 'broken-reference',
        severity: 'error',
        message: `Dark override references "${token.referencePath}", which does not exist.`,
        nodeId: nodeIdFor('system', path),
      });
    }
  }

  // --- 2 & 3. CSS usage checks ---
  const knownVars = new Set(graph.nodes.map((n) => n.cssVarName));
  const usedVars = new Set(tokenUsages.map((u) => u.varName));

  const locationsByVar = new Map<string, AuditLocation[]>();
  for (const u of tokenUsages) {
    const list = locationsByVar.get(u.varName) ?? [];
    list.push({ file: u.file, line: u.line });
    locationsByVar.set(u.varName, list);
  }

  for (const [varName, locations] of locationsByVar) {
    if (!knownVars.has(varName)) {
      issues.push({
        check: 'missing-token',
        severity: 'error',
        message: `Referenced in CSS but defined nowhere (${locations.length} usage${locations.length > 1 ? 's' : ''}).`,
        cssVar: varName,
        locations,
      });
    } else if (!varName.startsWith('--components-tokens--')) {
      const level = varName.startsWith('--system-tokens--') ? 'system' : 'global';
      const node = graph.nodes.find((n) => n.cssVarName === varName);
      issues.push({
        check: 'bad-usage',
        severity: 'warning',
        message: `CSS uses this ${level} token directly (${locations.length} usage${locations.length > 1 ? 's' : ''}) — should go through a component token.`,
        cssVar: varName,
        nodeId: node?.id,
        locations,
      });
    }
  }

  // --- 4. Raw values / level-skipping references ---
  for (const path in componentMap) {
    const token = componentMap[path];
    if (!token.isReference) {
      issues.push({
        check: 'raw-value',
        severity: 'warning',
        message: 'Component token has a raw value — it must alias a system token.',
        nodeId: nodeIdFor('component', path),
      });
      continue;
    }
    const targetPath = token.referencePath
      ? findReferencedPath(token.referencePath, lightSpace)
      : undefined;
    if (targetPath && globalMap[targetPath]) {
      issues.push({
        check: 'raw-value',
        severity: 'warning',
        message: 'Component token skips the system level and references a global directly.',
        nodeId: nodeIdFor('component', path),
        relatedNodeIds: [nodeIdFor('global', targetPath)],
      });
    }
  }
  for (const path in systemLightMap) {
    if (!systemLightMap[path].isReference) {
      issues.push({
        check: 'raw-value',
        severity: 'warning',
        message: 'System token has a raw value — it should alias a global token.',
        nodeId: nodeIdFor('system', path),
      });
    }
  }

  // --- 5. Duplicate resolved values (same level + type, light theme) ---
  const groups = new Map<string, string[]>();
  for (const node of graph.nodes) {
    const value = normalizeValue(node.resolvedValue, node.type, node.path);
    const key = `${node.level}|${node.type}|${value}`;
    const list = groups.get(key) ?? [];
    list.push(node.id);
    groups.set(key, list);
  }
  for (const [key, ids] of groups) {
    if (ids.length < 2) continue;
    const [level, type, value] = key.split('|');
    issues.push({
      check: 'duplicate',
      severity: 'info',
      message: `${ids.length} ${level} ${type} tokens resolve to ${value}.`,
      nodeId: ids[0],
      relatedNodeIds: ids.slice(1),
    });
  }

  // --- 6. Unused tokens ---
  const referencedIds = new Set(graph.edges.map((e) => e.to));
  for (const node of graph.nodes) {
    if (node.level === 'global' && !referencedIds.has(node.id)) {
      issues.push({
        check: 'unused',
        severity: 'info',
        message: 'No system token references this global value.',
        nodeId: node.id,
      });
    } else if (node.level === 'system' && !referencedIds.has(node.id)) {
      issues.push({
        check: 'unused',
        severity: 'info',
        message: 'No component token references this system token.',
        nodeId: node.id,
      });
    } else if (node.level === 'component' && !usedVars.has(node.cssVarName)) {
      issues.push({
        check: 'unused',
        severity: 'info',
        message: 'Defined in components.json but never used in any CSS file.',
        nodeId: node.id,
      });
    }
  }

  const byCheck = Object.fromEntries(
    AUDIT_CHECKS.map((c) => [c.id, [] as AuditIssue[]]),
  ) as Record<AuditCheckId, AuditIssue[]>;
  for (const issue of issues) byCheck[issue.check].push(issue);

  const counts: Record<AuditSeverity, number> = { error: 0, warning: 0, info: 0 };
  for (const issue of issues) counts[issue.severity]++;

  return { issues, byCheck, counts };
}
