/**
 * Screenshots live in `src/assets/projects/{slug}.webp` and are generated by
 * `pnpm build:screenshots`. Projects without a file fall back to the card's mockup cover.
 */
const files = import.meta.glob<string>('../assets/projects/*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
});

const bySlug: Record<string, string> = Object.fromEntries(
  Object.entries(files).map(([path, url]) => [path.split('/').pop()!.replace(/\.webp$/, ''), url]),
);

export function projectScreenshot(slug: string): string | undefined {
  return bySlug[slug];
}
